/* empty css                      */(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&r(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function r(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".demo-btn"),n=document.getElementById("gameIframe"),o=document.getElementById("closeIframeBtn");c&&n&&o&&(c.addEventListener("click",r=>{r.preventDefault();const e=c.getAttribute("data-game-url");n.src=e,n.style.display="block",o.style.display="flex"}),o.addEventListener("click",()=>{n.style.display="none",o.style.display="none",n.src=""}))});document.addEventListener("DOMContentLoaded",()=>{const c=document.querySelector(".menu-button"),n=c.querySelector(".icon"),o=document.querySelector(".modal"),r=document.querySelectorAll(".menu-list-item"),e=document.querySelector(".header");let t=!1;const s=`
<svg width="19" height="17" viewBox="0 0 19 17" fill="none" xmlns="http://www.w3.org/2000/svg">
  <rect width="19" height="3" fill="white" />
  <rect y="7" width="19" height="3" fill="white" />
  <rect y="14" width="19" height="3" fill="white" />
</svg>
    `,i=`
<svg width="28" height="28" viewBox="0 0 28 28" fill="none" xmlns="http://www.w3.org/2000/svg">
  <path d="M8 21L20.7279 8.27208" stroke="white" stroke-width="3" stroke-linecap="square" />
  <path d="M8 8L20.7279 20.7279" stroke="white" stroke-width="3" stroke-linecap="square" />
</svg>
    `;c.addEventListener("click",()=>{t=!t,n.innerHTML=t?i:s,t?d():l()}),r.forEach(u=>u.addEventListener("click",()=>{l(),n.innerHTML=s,t=!1})),window.addEventListener("scroll",a);function d(){o.style.display="block"}function l(){o.style.display="none"}function a(){e&&(window.scrollY>60?e.classList.add("header-scroll"):e.classList.remove("header-scroll"))}});document.addEventListener("DOMContentLoaded",()=>{function c(){const o=document.getElementById("site-header");return o?o.offsetHeight:0}function n(o){const r=document.getElementById(o);if(!r)return;const e=c(),t=r.getBoundingClientRect().top+window.pageYOffset-e;window.scrollTo({top:t,behavior:"smooth"})}if(document.querySelectorAll('a[href*="#"]').forEach(o=>{o.addEventListener("click",function(r){const e=this.getAttribute("href");if(!e)return;const[t,s]=e.split("#");if(!s)return;const i=window.location.pathname.split("/").pop();!(t===""||t==="./"||t===i||t==="./"+i)||!document.getElementById(s)||(r.preventDefault(),n(s))})}),window.location.hash){const o=window.location.hash.substring(1);setTimeout(()=>{n(o)},300)}});document.addEventListener("DOMContentLoaded",function(){const c=document.getElementById("cookie-popup"),n=document.getElementById("accept-cookies"),o=document.getElementById("decline-cookies");localStorage.getItem("cookiesAccepted")||(c.style.display="block"),n.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","yes"),c.style.display="none"}),o.addEventListener("click",()=>{localStorage.setItem("cookiesAccepted","no"),c.style.display="none"})});
//# sourceMappingURL=index.js.map
